### ISSUE TITLE
build.gradleの変更により、ビルドは出来るが実行時エラーになる。

### ISSUE THREAD

**Issue by DoranekoSystems** [DeNA/PacketProxy#111]
build.gradleのdependenciesが"compile"から"implementation"に変更されたことにより、「gradlew assemble」でコンパイルは通るのですが実行時に以下のエラーが発生します。(implementationをcompileに戻したら起動しました。)
依存関係を解決できていない問題によると思いますが、ビルド方法等を変えれば回避可能なのでしょうか?
抜本的な解決策が分からないため、投稿させていただきました。

環境:
OS:Microsoft Windows 11 Pro

----------------------------------------------------------------------------------------------------------------------
エラー内容:
Exception in thread "main" java.lang.NoClassDefFoundError: com/j256/ormlite/support/ConnectionSource
        at packetproxy.model.ClientCertificates.<init>(ClientCertificates.java:45)
        at packetproxy.model.ClientCertificates.getInstance(ClientCertificates.java:35)
        at packetproxy.common.ClientKeyManager.initialize(ClientKeyManager.java:36)
        at packetproxy.PacketProxy.<init>(PacketProxy.java:82)
        at packetproxy.PacketProxy.main(PacketProxy.java:52)
Caused by: java.lang.ClassNotFoundException: com.j256.ormlite.support.ConnectionSource
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more

**Comment by funa-tk** [comment]
実行ファイルにライブラリが含まれないようになってしまったようです。
`java -jar build/libs/PacketProxy.jar` ではなく `./gradlew run` で起動できるはずですので試してみてもらえませんでしょうか？

**Comment by funa-tk** [comment]
マニュアルの方も `./gradlew run` で起動するように修正しました。

**Comment by DoranekoSystems** [comment]
```gradlew run```で無事起動しました。
ご対応有難うございます。
