### ISSUE TITLE
Windows版で起動時にHistoryを削除すると例外が発生してGUIが表示されない

### ISSUE THREAD

**Issue by cos65535** [DeNA/PacketProxy#28]
以下のような例外が発生してGUIが表示されない。

```2019/10/01 17:58:38       drop history...
2019/10/01 17:58:38       C:\Users\shingo.mori\.packetproxy\db\resources.sqlite3 -> C:\Users\shingo.mori\.packetproxy\db\tmp.sqlite3: プロセスはファイルにアクセスできません。別のプロセスが使用中です。
​
2019/10/01 17:58:38       sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
2019/10/01 17:58:38       sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
2019/10/01 17:58:38       sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
2019/10/01 17:58:38       sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
2019/10/01 17:58:38       java.nio.file.Files.move(Files.java:1395)
2019/10/01 17:58:38       packetproxy.model.Database.dropPacketTableFaster(Database.java:94)
2019/10/01 17:58:38       packetproxy.model.Packets.<init>(Packets.java:54)
2019/10/01 17:58:38       packetproxy.model.Packets.getInstance(Packets.java:32)
2019/10/01 17:58:38       packetproxy.gui.GUIHistory.<init>(GUIHistory.java:128)
2019/10/01 17:58:38       packetproxy.gui.GUIHistory.getInstance(GUIHistory.java:97)
2019/10/01 17:58:38       packetproxy.gui.GUIHistory.getInstance(GUIHistory.java:90)
2019/10/01 17:58:38       packetproxy.gui.GUIMain.getGUIHistory(GUIMain.java:165)
2019/10/01 17:58:38       packetproxy.gui.GUIMain.<init>(GUIMain.java:112)
2019/10/01 17:58:38       packetproxy.gui.GUIMain.getInstance(GUIMain.java:70)
2019/10/01 17:58:38       packetproxy.PacketProxy.startGUI(PacketProxy.java:94)
2019/10/01 17:58:38       packetproxy.PacketProxy.start(PacketProxy.java:84)
2019/10/01 17:58:38       packetproxy.PacketProxy.main(PacketProxy.java:51)
java.nio.file.FileSystemException: C:\Users\shingo.mori\.packetproxy\db\resources.sqlite3 -> C:\Users\shingo.mori\.packetproxy\db\tmp.sqlite3: プロセスはファイルにアクセスできません。別のプロセスが使用中です。
​
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
        at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
        at java.nio.file.Files.move(Files.java:1395)
        at packetproxy.model.Database.dropPacketTableFaster(Database.java:94)
        at packetproxy.model.Packets.<init>(Packets.java:54)
        at packetproxy.model.Packets.getInstance(Packets.java:32)
        at packetproxy.gui.GUIHistory.<init>(GUIHistory.java:128)
        at packetproxy.gui.GUIHistory.getInstance(GUIHistory.java:97)
        at packetproxy.gui.GUIHistory.getInstance(GUIHistory.java:90)
        at packetproxy.gui.GUIMain.getGUIHistory(GUIMain.java:165)
        at packetproxy.gui.GUIMain.<init>(GUIMain.java:112)
        at packetproxy.gui.GUIMain.getInstance(GUIMain.java:70)
        at packetproxy.PacketProxy.startGUI(PacketProxy.java:94)
        at packetproxy.PacketProxy.start(PacketProxy.java:84)
        at packetproxy.PacketProxy.main(PacketProxy.java:51)```

**Comment by funa-tk** [comment]
#25と同じissueです。
