### ISSUE TITLE
java.util.MissingResourceException when run on Linux 

### ISSUE THREAD

**Issue by jpopxfile** [DeNA/PacketProxy#46]
```
➜  PacketProxy git:(master) java -jar ./build/libs/PacketProxy.jar 
Exception in thread "main" java.lang.ExceptionInInitializerError
        at packetproxy.common.FontManager.getLocaleFontStyles(FontManager.java:58)
        at packetproxy.common.FontManager.createUIFont(FontManager.java:65)
        at packetproxy.common.FontManager.<init>(FontManager.java:46)
        at packetproxy.common.FontManager.getInstance(FontManager.java:22)
        at packetproxy.gui.GUIMain.setLookandFeel(GUIMain.java:185)
        at packetproxy.gui.GUIMain.<init>(GUIMain.java:110)
        at packetproxy.gui.GUIMain.getInstance(GUIMain.java:77)
        at packetproxy.PacketProxy.startGUI(PacketProxy.java:99)
        at packetproxy.PacketProxy.start(PacketProxy.java:89)
        at packetproxy.PacketProxy.main(PacketProxy.java:56)
Caused by: java.util.MissingResourceException: Can't find bundle for base name strings, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
        at packetproxy.common.I18nString.<clinit>(I18nString.java:9)
        ... 10 more
```

**Comment by funa-tk** [comment]
Thank you for the stacktrace.
I'll check the issue and fix it in a few days.

**Comment by funa-tk** [comment]
I've fixed this issue and pushed a patch to master branch.

**Comment by jpopxfile** [comment]
It works well now! Thanks!
